// <auto-generated />
namespace ASP_MyBSNList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AppModel_Id_IntToByte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppModel_Id_IntToByte));
        
        string IMigrationMetadata.Id
        {
            get { return "202008201946594_AppModel_Id_IntToByte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
