// <auto-generated />
namespace ASP_MyBSNList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DB_1309 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_1309));
        
        string IMigrationMetadata.Id
        {
            get { return "202009131307052_DB_1309"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
